services:
  - type: web
    name: whatsapp-reminder-monolith
    env: node
    rootDir: backend
    buildCommand: npm install && npx puppeteer browsers install chrome
    startCommand: node server.js
    envVars:
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: MONGO_URI
        sync: false
      - key: ADMIN_USERID
        value: saikiranbeesa@gmail.com
      - key: ADMIN_PASSWORD
        value: Reminder@10
      - key: JWT_SECRET
        generateValue: true
